version: 2

project_name: sol

before:
  hooks:
    - go mod tidy

builds:
  - id: sol
    main: .
    binary: sol
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/menor/sol/cmd.version={{.Version}}
      - -X github.com/menor/sol/cmd.commit={{.Commit}}
      - -X github.com/menor/sol/cmd.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: menor
    name: sol
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
